### ISSUE TITLE
add support for user tasks

### ISSUE THREAD

**Issue by nareshv** [linkedin/cruise-control-ui#1]
CC support User-Task-Id header for long running tasks. Leverage this feature in addition to current sessions implementation.

**Comment by ldrrp** [comment]
Is this tasks like trigger a script on an alert?

**Comment by nareshv** [comment]
@ldrrp , user tasks are feature of [cruise control](https://github.com/linkedin/cruise-control/wiki/REST-APIs). Right now cruise control supports both session & task id based responses and are in the process of moving to task id based approach. 

Regarding your question, cruise control already supports alerting on various [conditions](https://github.com/linkedin/cruise-control/wiki/Configurations).

**Comment by nareshv** [comment]
CORS cases are not completely  handled due to blocker on https://github.com/linkedin/cruise-control/issues/585

**Comment by nareshv** [comment]
available in v0.3.0
