### ISSUE TITLE
what's correct format for Excluded Topics in CC UI Kafka Cluster Administration

### ISSUE THREAD

**Issue by rumwei** [linkedin/cruise-control-ui#123]
when i add Excluded Topics in tab Kafka Cluster Administration
<img width="564" alt="image" src="https://github.com/linkedin/cruise-control-ui/assets/16240456/3be03b61-e886-4c81-8b39-c8894d313d72">
only specify one topic works well, in response
```java
{
  "summary": {
    ...
    "excludedTopics": [
      "__consumer_offsets"
    ],
    "numLeaderMovements": 8
  },
```

when i try to exclude multi topics with
1. a,b
2. a&&b
3. a||b
4. [a,b]
5. {a,b}
it does not work properly with response below
```java
{
  "summary": {
    ...
    "excludedTopics": [],
    "numLeaderMovements": 8
  },
```

my question is how can i specify more than one topic in Excluded Topics show above?

thanks~

**Comment by joseronierison** [comment]
up

**Comment by rumwei** [comment]
Got it. The correct format for multi topics is a|b|c
