### ISSUE TITLE
how to identify the minimum supported version of cruise control for CC UI

### ISSUE THREAD

**Issue by shanrd7** [linkedin/cruise-control-ui#2]

**Comment by nareshv** [comment]
ui supports all releases of CC(including 2.x branch) as majority of the code is written in backward compatible way.

grab the latest from master and deploy.

let us know if you see any issues.

**Comment by shanrd7** [comment]
Thanks will do

**Comment by nareshv** [comment]
@shanrd7 , anything else required here ?
