### ISSUE TITLE
Cruise Control Ui - Won't show up the dropdown to navigate

### ISSUE THREAD

**Issue by shanrd7** [linkedin/cruise-control-ui#22]
dist
├── index.html
└── static
    ├── cc-logo.png
    ├── config.csv
    ├── css
    │   ├── app.css
    │   └── app.css.map
    └── js
        ├── app.js
        ├── manifest.js
        └── vendor.js

**Comment by shanrd7** [comment]
![image](https://user-images.githubusercontent.com/45983867/57022873-79bff800-6bfe-11e9-9dac-022d60a64f22.png)

**Comment by shanrd7** [comment]
@nareshv I did verified my config.csv in both levels.

**Comment by nareshv** [comment]
@shanrd7 can you open the 'Preferences -> config.csv Insights' ? and see if its showing the entries there ?

Also, which version are you using ?

**Comment by shanrd7** [comment]
I am on version 0.1.0
Some how it picked after multiple restarts

**Comment by nareshv** [comment]
marking as resolved.
