### ISSUE TITLE
Feature Request: expose monitor pause/resume endpoint

### ISSUE THREAD

**Issue by BrianGallew** [linkedin/cruise-control-ui#23]
It would be awesome if the `Monitor State` pane included a button to toggle the current monitoring state.

**Comment by nareshv** [comment]
It was there, for some reason i have to hide it .Lemme add it back.

**Comment by BrianGallew** [comment]
Thanks!  I *presume* the "resume" endpoint was hidden because you
auto-pause while movements are in progress, but when we're doing
maintenance or manual updates to the cluster, it would be good to be able
to set this a little more easily.

**Comment by nareshv** [comment]
Controls are added @ `Cruise Control State` Tab > `Monitor State` view
<img width="373" alt="resume" src="https://user-images.githubusercontent.com/1161803/58676626-89a23780-8376-11e9-8a7f-a5850a1a1c8d.png">
<img width="373" alt="pause" src="https://user-images.githubusercontent.com/1161803/58676627-89a23780-8376-11e9-9e85-7a4a636a9ba5.png">

Small icon is clickable to toggle the state.

**Comment by BrianGallew** [comment]
Thanks!
