### ISSUE TITLE
Running Application Within Cruise Control (Embedded Mode) but after Hitting http://$mykcchost:80/ is not show the cruise control frontend interface

### ISSUE THREAD

**Issue by shanrd7** [linkedin/cruise-control-ui#3]
MonitorState: {state: RUNNING(18.400% trained), NumValidWindows: (1/1) (100.000%), NumValidPartitions: 210/210 (100.000%), flawedPartitions: 0}
ExecutorState: {state: NO_TASK_IN_PROGRESS}
AnalyzerState: {isProposalReady: true, readyGoals: [NetworkInboundUsageDistributionGoal, CpuUsageDistributionGoal, PotentialNwOutGoal, NetworkInboundCapacityGoal, LeaderBytesInDistributionGoal, DiskCapacityGoal, ReplicaDistributionGoal, RackAwareGoal, TopicReplicaDistributionGoal, NetworkOutboundCapacityGoal, CpuCapacityGoal, DiskUsageDistributionGoal, NetworkOutboundUsageDistributionGoal, ReplicaCapacityGoal]}
AnomalyDetectorState: {selfHealingEnabled:[GOAL_VIOLATION, METRIC_ANOMALY, BROKER_FAILURE], selfHealingDisabled:[], recentGoalViolations:[], recentBrokerFailures:[], recentMetricAnomalies:[]}

Monitored Windows [Window End_Time=Data_Completeness]:
{1550179500000=100.000%}

Goal Readiness:
                                     RackAwareGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.000, includedAllTopics=true), Ready
                               ReplicaCapacityGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.000, includedAllTopics=true), Ready
                                  DiskCapacityGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=true), Ready
                        NetworkInboundCapacityGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=true), Ready
                       NetworkOutboundCapacityGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=true), Ready
                                   CpuCapacityGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=true), Ready
                           ReplicaDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.000, includedAllTopics=true), Ready
                                PotentialNwOutGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=false), Ready
                         DiskUsageDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=true), Ready
               NetworkInboundUsageDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=false), Ready
              NetworkOutboundUsageDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=false), Ready
                          CpuUsageDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=false), Ready
                      TopicReplicaDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.000, includedAllTopics=true), Ready
                     LeaderBytesInDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=false), Ready

**Comment by shanrd7** [comment]
Kafka cruise control works

**Comment by nareshv** [comment]
@shanrd7 , the build artifacts of cruise-control-ui `(i.e npm build generated files)` should be deployed within the `cruise-control/cruise-control-ui/dist` directory.

For example, this is how the structure looks like

```
bash-$ pwd
~/cruise-control
bash-$ tree ./cruise-control-ui/dist/
cruise-control-ui/dist/
├── index.html
└── static
    ├── config.csv
    ├── css
    │   ├── app.css
    │   └── app.css.map
    ├── js
    │   ├── app.js
    │   └── manifest.js

3 directories, 7 files
```

CC recognizes these paths and serves the `index.html` from this directory. 

If you are using a modern CC, then the `config/cruisecontrol.properties` exposes a property `webserver.ui.diskpath=./cruise-control-ui/dist/`, which should match where `cruise-control-ui` is deployed.

**Comment by shanrd7** [comment]
Thanks @nareshv this makes more sense, went passed through the UI issue. Does the data load on Ui will take time as it had to load complete data ?
I see this on ui "Error: Network Error"

**Comment by shanrd7** [comment]
I don't think there should not be network issue because the KCC load and populates properly

**Comment by shanrd7** [comment]
I figured out the issue is with config.csv file wrongly prompted

**Comment by nareshv** [comment]
@shanrd7 , are you able to use the  CCFE now ?

**Comment by shanrd7** [comment]
@nareshv Thanks a lot it works

**Comment by chetann** [comment]
@shanrd7 @nareshv 
`
I figured out the issue is with config.csv file wrongly prompted` can you share some more light on the error you found in config.csv and how you fixed it? I am also facing same issue but during multiple cluster set up.

**Comment by aws0** [comment]
I faced same issue, it turned out to be a missing "/" at the end of the path in config.csv , the error is very difficult to troubleshoot especially since all manual curl calls were working fine
