### ISSUE TITLE
Untar files seems different i dont see dist directory

### ISSUE THREAD

**Issue by shanrd7** [linkedin/cruise-control-ui#35]
As per your doc latest compiled artifact has different directory structure as below
 tar zxvf cruise-control-ui.tar.gz
x cruise-control-ui/
x cruise-control-ui/index.html
x cruise-control-ui/Changelog
x cruise-control-ui/README.md
x cruise-control-ui/static/
x cruise-control-ui/static/cc-logo.png
x cruise-control-ui/static/css/
x cruise-control-ui/static/js/
x cruise-control-ui/static/config.csv
x cruise-control-ui/static/js/manifest.js
x cruise-control-ui/static/js/vendor.js
x cruise-control-ui/static/js/app.js
x cruise-control-ui/static/css/app.css
x cruise-control-ui/static/css/app.css.map

Following below doc
https://github.com/linkedin/cruise-control-ui/wiki/Single-Kafka-Cluster

**Comment by shanrd7** [comment]
npm install
npm WARN saveError ENOENT: no such file or directory, open '/cruise-control-ui/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/cruise-control-ui/package.json'
npm WARN cruise-control-ui No description
npm WARN cruise-control-ui No repository field.
npm WARN cruise-control-ui No README data
npm WARN cruise-control-ui No license field.

up to date in 0.516s
found 0 vulnerabilities

**Comment by ishita07-danaher** [comment]
any update on this ? I am also facing the same issue

**Comment by nareshv** [comment]
pushed in v0.3.1 release https://github.com/linkedin/cruise-control-ui/releases/tag/v0.3.1
