### ISSUE TITLE
Unable to access CC-UI frontend

### ISSUE THREAD

**Issue by CayoEduardo** [linkedin/cruise-control-ui#48]
I'm trying to connect to CC UI from http:localhost:8090 but the page doesn't load. if I use curl localhost:8090 from inside the container it gets the html for the webpage, but if i try to connect using the browser it doesn't respond. 

My config.csv : dev,dev,/kafkacruisecontrol/
cruisecontrol.properties:
- HTTP listen port
webserver.http.port=8090

- HTTP listen address
webserver.http.address=0.0.0.0

webserver.api.urlprefix=/kafkacruisecontrol/*

- Location where the Cruise Control frontend is deployed
webserver.ui.diskpath=/opt/cruise-control/cruise-control-ui/dist

- URL path prefix for UI
- (dont forget the ending *)
webserver.ui.urlprefix=/

>> ********************************************* <<
>> Application directory            : /opt/cruise-control
>> REST API available on            : /kafkacruisecontrol/*
>> Web UI available on              : /*
>> Web UI Directory                 : ./cruise-control-ui/dist/
>> Cookie prefix path               : /
>> Kafka Cruise Control started on  : http://0.0.0.0:8090/
>> CORS Enabled ?                   : false
>> ********************************************* <<*

**Comment by nareshv** [comment]
@CayoEduardo are you using this inside docker ? Can you see if the 8090 port is exposed outside container ?

**Comment by CayoEduardo** [comment]
I'm using on Kubernetes and Port 8090 is exposed through a service

**Comment by CayoEduardo** [comment]
I solved the issue. Although the port was beeing exposed, i needed to port forward using `kubectl port-forward svc/cruise-control 8090:8090` then i could access on my browser through http://localhost:8090
