### ISSUE TITLE
Change instance name when running in embedded mode

### ISSUE THREAD

**Issue by d-shi** [linkedin/cruise-control-ui#5]
Is there a way to change both the logical group name and CC UI instance name when running in embedded mode? I tried changing the first two columns in `static/config.csv` but the UI always shows `dev>>dev`. It would be nice since we have multiple environments and would like to keep the UI instance separate for each environment as well.

**Comment by nareshv** [comment]
Hi @d-shi, UI picks the values from `static/config.csv`. As long as the browser gets the right contents, you should be able to see the right names on the UI. I am assuming, the contents of `config.csv` might be cached on the browser ?

**Comment by d-shi** [comment]
I confirmed the contents of `static/config.csv` were the following:

```
root@kafka-cc-75f66f5449-sr7ps:/cruise-control/cruise-control-ui/static# cat config.csv
dai,test,http://localhost:9000/kafkacruisecontrol
```

I then tried in an incognito browser, and also in a different browser where I had never navigated to kafka cruise control before, also in incognito. In both browsers, I still see this:

<img width="330" alt="screen shot 2019-02-19 at 15 53 44" src="https://user-images.githubusercontent.com/6404307/53046785-debcdc00-345e-11e9-9a23-54809b58fd3e.png">

Am I doing something wrong?

**Comment by nareshv** [comment]
Actually, the contents on disk are correct, its just that when its served via HTTP, i am guessing the browser would have cached it (http://$host:$port/static/config.csv in browser shows old content), thats why the app is seeing old values.

Let me try to add a time sensitive url param to `static/config.csv`. This should help cases like this.

**Comment by nareshv** [comment]
@d-shi , pushed code to master which had this `cache busting` feature while downloading `config.csv`. This should take care of issue you are seeing

**Comment by d-shi** [comment]
I pulled the latest master and rebuilt my image. However I am still seeing the same problem. I cleared my browser cache, and also looked via browser inspect at the config.csv file that it downloads, and it is brand new as can be confirmed by the `?_t=1550689185150` timestamp in the filename:

<img width="556" alt="screen shot 2019-02-20 at 14 09 03" src="https://user-images.githubusercontent.com/6404307/53117609-4b94ac80-3519-11e9-833d-d2bca186ccbb.png">

I can clear cache and refresh the page, and the timestamp on that file will change to the latest time. However, as you can see, the contents still show `dev,dev,/kafkacruisecontrol/`. Any ideas where that is coming from?

**Comment by d-shi** [comment]
Actually I found that there is another file called `dist/static/config.csv` which is what is actually being served rather than `static/config.csv`. If I modify `dist/static/config.csv` then it works like I expect. Is this intended and the documentation is just wrong?

**Comment by nareshv** [comment]
You are right. I have corrected the documentation in README.md file.

As part of build process (`npm run build`), the `static/config.csv` is copied to `dist/static/config.csv`. Later when we serve this directly via CC, we get to see only the files under `cruise-control-ui/dist/*`. So the changes made to `static/config.csv` weren't visible, until next `npm run build`.

I hope this clarifies things.

**Comment by d-shi** [comment]
OK, thank you for confirming!
