### ISSUE TITLE
Add charts and visualisation

### ISSUE THREAD

**Issue by optplx** [linkedin/cruise-control-ui#54]
I am currently working on adding charts based on cruise control APIs to visualise things such as:
- current CPU distribution across nodes per topic
- current leadership and replica distribution across brokers per topic
- same as above, but based on proposals to fully visualize what the proposal would look like on the clusters

Would you be interested in a PR about it? For now we did it in another tool but this could be ported in the CC ui.

See for example:
![image](https://user-images.githubusercontent.com/10009508/98692092-052b5500-236f-11eb-8f76-2c1d73736e91.png)

**Comment by nareshv** [comment]
This would be great addition. Few thoughts here

Right now there is no API to enumerate the topics in the cluster. Except via https://github.com/linkedin/cruise-control/issues/361

Where are you planning to put these charts ?

**Comment by optplx** [comment]
`Right now there is no API to enumerate the topics in the cluster`
==> I currently rely on 2 endpoints:
- `GET /kafkacruisecontrol/partition_load` to get all what currently exist on a given cluster (cpu/leaders/replicas per topic and per broker)
- `GET /kafkacruisecontrol/proposals` with `verbose=true` to analyze the proposed plans. I usually do a diff between the proposal and the partition_load to get the final result, since the proposal only gives the moves to be done

`Where are you planning to put these charts ?`
- For the existing leaders and replicas distribution, we could add a tab near `kafka cluster state`, or even directly inside the cluster state tab?
- We also have a global tab where we see all CPU repartition for all clusters, this gives a quick overview of the current state of all our clusters. This could go in summary
- For the proposal analysis, I would see a new tab where the user can select the goals and see how it impacts the distributions. here is what we have currently 
![image](https://user-images.githubusercontent.com/10009508/98919503-2dca6080-24cf-11eb-8b6b-add31cfdc546.png)

what do you think? do you have other ideas?

**Comment by nareshv** [comment]
Another question: What does the x & y axis indicate in the graphs for a given topic ?

**Comment by optplx** [comment]
x is the broker ID and y is the number of leaders, or the number of replicas, depending on the selected view. 

Also on our "CPU" view, we have x=broker ID and y = cpu per topic, in a stacked view. e.g 
![image](https://user-images.githubusercontent.com/10009508/99051832-ced11e00-2598-11eb-8832-194ffc9cd7ad.png)

**Comment by nareshv** [comment]
Just to confirm the list of charts

1. Select Topic > View CPU Distribution (**x-axis**: broker-ids, **y-axis**: cpu %)
2. Select Topic > View Leader Distribution (**x-axis**: broker-ids, **y-axis**: total-leaders-on-this-broker ?)
3. Select Topic > View Replica Distribution (**x-axis**: broker-ids, **y-axis**: total-replicas-on-this-broker ?)

Making these generic: I'd suggest these

Select Topic > View $resource distribution (**x-axis**: broker-ids, **y-axis**: $resource $units)

Where

- $resource: Cpu %, Disk utilization %, Network Utilization % 
- $units: Absolute value, or %

Lets try to come up with a new component `Ex: ChartsAndVisualization.vue` and in that we can add these widgets (from your screenshots

1. Topic selection (dropdown vs autocomplete) - (BONUS: For 1k+ topics how does the UX gonna look like)
2. Upon topic selected
3. Show one graph for each $resource in the same UI (If we support 3 $resources, show the $cpu, $disk, $network_in, $network_out) graphs (BONUS: Handle clusters > 50-100+ nodes in the chart)

Required for usability:

1. (chart) Axis Labeling
2. (chart) Showing a Legend
3. (license) choice of library which is light weight and the license is MIT or similar

Please help share any final mocks for these charts you may have for the 4 types of resources. Also, share your thoughts around handling large topics & large clusters to minimize usability/performance challenges.

**Comment by optplx** [comment]
Hi, sorry for the lack of response here we have an hard Q4 this year
Can I come back to you about it in January?

**Comment by nareshv** [comment]
Sure, i guess that should be ok.

**Comment by optplx** [comment]
Hello @nareshv, I am now available to work on this topic.

To answer your questions: 
- you almost get the list of charts correctly, just a few points to clarify what we have:
  - For leaders and replicas: We don't select the topics, we just select the cluster + the resource, and then we display the charts for all the topics (could be paginated I guess). We call these views "detailed views", but we don't have CPU in here (could be added though). 
  - For the CPU, we have one single page showing all charts for all clusters (charts are stacked, meaning that you have one single chart per cluster, showing the CPU consumed by each topic for each broker). This basically provides a quick overview of all the clusters to quickly spot if we have one imbalanced. Hence we call this view the "overview". We could have one per group of clusters as well instead of one single page (e.g group per geographical region).

Does that makes sense for you? Maybe in a second iteration we could imagine being able to chose other resources (leaders, replicas) in the overview view as well. But in a first iteration I propose to go with what we have currently, if that's fine for you (happy to discuss this)

- Topic selection: good point with the 1k+ topics, maybe a dropdown showing the first 10 topics + autocomplete? I guess that something we will have to experiment to find the best option, I have no solution right now :/
- Upon topic selected, show 1 graph for each resource: as explained above, what we find interesting in the detailed view is to be able to compare brokers together. Thus we display the graphs for all the topics in the same view. For charts with 50-100+ nodes, same I have no solution right now but we could probably do something based on some kind of pagination as well

Regarding the usability things: 
- Chart labelling and legend is definitely doable. I have removed them on our tool because it was making the views hard to read IMO. but this is not a technical issue, I have no strong opinion on this
- The library I am using currently is https://developers.google.com/chart, which is completely free for all uses: commercial, governmental, personal or educational. I have also spotted this one https://www.chartjs.org/ which I have not used so far but looks nice. Happy to dig another one if you have one to suggest

Happy to discuss all the points if you like, do you have a Slack or similar? Or do you prefer to use this github issue?

**Comment by nareshv** [comment]
1. On the charting library, lets prefer the one which works standalone and doesn't depend on external network resources on Internet. chartjs has MIT license which is acceptable for most cases. I would prefer going with chartjs
2. Your proposals above seems ok to me.

Just for completeness, lets enumerate the list of detailed charts that we are going to come up with and we can actually create separate tasks per chart if required to measure the progress, what do you think ?

```
**Example**: Chart-1: Per cluster, current cpu utilization chart
**Input**: Cluster, Resource=cpu
**Output**: Bar graph with broker-ids on x-axis and % cpu utilization on y-axis
**Refresh**: Manual or Automatically every 5 secs, etc
**Features**: Checkbox to disable auto-refresh (for clusters with large brokers)
```

**Comment by optplx** [comment]
We could implement auto-refresh, but since the values displayed are max or average based on large time windows, I am not sure if we want to go this way. (Here for example we have a 1 day time window, and if I am not wrong it is 5 minutes by default)

Chart-1: Per cluster, current cpu utilization chart
**Input**: Cluster, Resource=cpu
**Output**: Bar graph with broker-ids on x-axis and % cpu utilization on y-axis (with detail per topic)
**Assumption**: we assume that CPU is consumed by leaders only. We found out that this is a pretty good assumption based on our monitoring (cpu user + cpu system gives similar values to sum of CPU consumed considering leaders only)

Chart-2: List of per cluster, current leaders distribution across brokers charts
**Input**: Cluster, Resource=leaders
**Output**: List of Bar graphs (1 per topic) with broker-ids on x-axis and number of leaders per broker (stackable into 1 single graph)

Chart-3: List of per cluster, current replicas distribution across brokers charts
**Input**: Cluster, Resource=replicas
**Output**: List of Bar graphs (1 per topic) with broker-ids on x-axis and number of replicas per broker (stackable into 1 single graph)

Chart-4: Global "monitoring" page, List of per cluster, current cpu utilization charts (for all clusters)
**Input**: Cluster, Resource=cpu
**Output**: Bar graph with broker-ids on x-axis and % cpu utilization on y-axis (with detail per topic)

Chart-5: we have not implemented this yet, but I think it could be nice to have a radar measuring the spread of network in/out, of cpu and of number of leaders/replicas for example (like this https://www.chartjs.org/docs/latest/charts/radar.html)
**Input**: Cluster, Resource=radar
**Output**: Radar measuring the deviation (or other mathematic metric?)

For chats 2 and 3, we can also display additional informations such as the replication factor and the size of the topic (e.g within the title of the graph)

I should be able to push a first PR soon for the number of leaders so that we have a first base for further discussion

Please let me know if you have any comments about this
