### ISSUE TITLE
"npm: 6.7.0 should be undefined" error message when running npm run dev

### ISSUE THREAD

**Issue by awartika** [linkedin/cruise-control-ui#6]
I am trying to start the application in a docker container. When I start the app with npm run dev, I get the following error:

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cruise-control-ui@0.1.0 start: `test -d cruise-control-ui && cd cruise-control-ui; node build/dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cruise-control-ui@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /app/.npm/_logs/2019-03-01T19_28_47_361Z-debug.log

**Comment by nareshv** [comment]
Do you have all the dependencies installed ? i am suspecting something to do with the node environment inside docker.

**Comment by awartika** [comment]
What is the node and npm version that CC ui expects ? I thinker's something to do with the versions. Our build environment doesn't support range patterns, so I removed the npm version and changed the node version to 11.10.0 in here:

"engines": {
    "node": ">= 4.0.0",
    "npm": ">= 3.0.0"
},

Unfortunately that is causing the failure above.

**Comment by nareshv** [comment]
we have tested this with node-6+. If your build env downloads the node/npm from the package.json then its a bit tricky as you don't have control over build process.

I'd suggest you can get the latest stable version of node/npm and build it or use the already build CCFE artifacts which shouldn't cause any trouble.

**Comment by nareshv** [comment]
@awartika , i have created wiki to explain how to use CCFE with docker https://github.com/linkedin/cruise-control-ui/wiki/CCFE-(Dev-Mode)---Docker

**Comment by nareshv** [comment]
This occurs when the node modules are not installed. please install them before running the dev server. Also above doc should be helpful for docker setups.
