### ISSUE TITLE
Cruise Control UI Compatibility 

### ISSUE THREAD

**Issue by qz-fordham** [linkedin/cruise-control-ui#66]
Hi,
I am using Cruise Control 2.5.x, and I was wondering which UI branch or tag is best for Cruise Control 2.5.33? Or is there a Wiki page for me to read? I am having issue get certain goals from UI (I meant from **Kafka Cluster Administration** page). For example, CC 2.5.33 has `RackAwareDistributionGoal` but CC-UI v0.3.4 doesn't have that goal. Maybe I am using the wrong branch. Please help. Thank you in advance.

**Comment by nareshv** [comment]
UI is compatible with multiple versions of the CC by dynamically discovering the responses. Can you submit a PR with the goal enumeration ?

**Comment by nareshv** [comment]
closing ticket.
