### ISSUE TITLE
Seeing network error in CC UI

### ISSUE THREAD

**Issue by awartika** [linkedin/cruise-control-ui#7]
I am running CC server on a different node than CC UI and in the config.csv, I have specified the complete hostname and port for CC server. However when I start CC UI and select the instance, i get "network error" for all the selections. I can use the REST APIs and get the CC status successfully from the node I am running CC UI on which means I can access the server on the host and port. Why is the UI showing network error ?

**Comment by awartika** [comment]
Can I run CC server and CCFE on different nodes ?

**Comment by nareshv** [comment]
@awartika , even though CCFE is hosted on a webserver (either CC or Apache/Nginx), the application runs within the webbrowser and theAPI  Access rules are applicable from the web-browser (i.e browser makes calls to the remote CC end points either via Reverse Proxy method or CORS Method).

Based on the notes you have shared, you are accessing the CC REST API via [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) method. This is a bit tricky than Reverse proxy method and requires CORS method to be enabled in the CC servers (https://github.com/linkedin/cruise-control/blob/master/config/cruisecontrol.properties#L247). By default this is disabled on all CC for security reasons.

I'll add a wiki section regarding this in the next couple of days.

Regarding  your question of CC & CCFE, yes they can run on different servers without any problem.

**Comment by awartika** [comment]
Thanks for your response. So if I enable the cors method on CC servers, I will be able to access ?

**Comment by nareshv** [comment]
Yes, i woudn't recommend CORS if the environment in an unsafe environment.

**Comment by nareshv** [comment]
CORS is blocked on a cruise-control server side code change at the moment.

**Comment by nareshv** [comment]
https://github.com/linkedin/cruise-control/commit/9c7ad36017421b2a0265c0d1ab024730b7d4e9de onwards CORS support is there in cruise-control.

Config changes required on CC to use CORS is documented in https://github.com/linkedin/cruise-control-ui/wiki/CORS-Method
