### ISSUE TITLE
webserver.ui.urlprefix Clarification

### ISSUE THREAD

**Issue by kevinbrightincontact** [linkedin/cruise-control-ui#74]
Hello, we are trying to expose the cruse control ui through our ingress on a predetermined shared port.

I'm trying to set webserver.ui.urlprefix to /cruisecontrol-ui/* so that when requests come in through the ingress they are forwarded correctly. Right now I can access index.html through our ingress, but subsequent requests to static resources fail.

However, if I set the value to webserver.ui.urlprefix in the properties and restart I'm not even able to get a successful response using curl on localhost. Am I misunderstanding the usage of webserver.ui.urlprefix or are there additional configurations that are needed for this?

webserver.ui.urlprefix=/*
**curl http://127.0.0.1:9090**
`<!doctype html><html lang=en><head><meta charset=utf8><meta name=viewport content="width=device-width,initial-scale=1,shrink-to-fit=no"><title>Kafka Cruise Control UI</title><link href=/static/css/app.css rel=stylesheet></head><body><div id=app></div><script type=text/javascript src=/static/js/manifest.js></script><script type=text/javascript src=/static/js/vendor.js></script><script type=text/javascript src=/static/js/app.js></script></body></html>`

webserver.ui.urlprefix=/cruisecontrol-ui/*
**curl http://127.0.0.1:9090/cruisecontrol-ui**
**curl http://127.0.0.1:9090**
**curl http://127.0.0.1:9090/cruisecontrol-ui/index.html**
`<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404 Not Found</h2>
<table>
<tr><th>URI:</th><td>/</td></tr>
<tr><th>STATUS:</th><td>404</td></tr>
<tr><th>MESSAGE:</th><td>Not Found</td></tr>
<tr><th>SERVLET:</th><td>org.eclipse.jetty.servlet.ServletHandler$Default404Servlet-ce5a68e</td></tr>
</table>
<hr><a href="https://eclipse.org/jetty">Powered by Jetty:// 9.4.35.v20201120</a><hr/>

</body>
</html>
[root@cruisecontrol-84d6868959-tdw9q cruise-control]# curl http://localhost:9090/cruisecontrol-ui
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404 Not Found</h2>
<table>
<tr><th>URI:</th><td>/cruisecontrol-ui</td></tr>
<tr><th>STATUS:</th><td>404</td></tr>
<tr><th>MESSAGE:</th><td>Not Found</td></tr>
<tr><th>SERVLET:</th><td>default</td></tr>
</table>
<hr><a href="https://eclipse.org/jetty">Powered by Jetty:// 9.4.35.v20201120</a><hr/>

</body>
</html>`

**Comment by nareshv** [comment]
afaik, the backend code (cruisecontrol) doesn't support changing it.

**Comment by bachmanity1** [comment]
Hi @nareshv @kevinbrightincontact , I'm facing exactly same problem. Is there any way to override base path from which static resources are served? For example, I want to change this `/static/js/app.js ` to something like this `/path/to/ui/static/js/app.js`. Thanks in advance!
