### ISSUE TITLE
Many clusters - no scroll on nav menu

### ISSUE THREAD

**Issue by DaveCLowe** [linkedin/cruise-control-ui#76]
When Cruise Control is managing many, many clusters - the bottom items on the nav menu aren't accessible as there is no scrollbar available. I'm happy to raise a PR to add scroll to the nav if that's the path forward.

**Comment by nareshv** [comment]
Can you help share an anonymized screenshot of the problem ? We are happy to take PRs that fixes the potential problem.

**Comment by nareshv** [comment]
Closing this, please re-open with screenshot to understand the problem better. This helps us provide some fix to address the issue.
