### ISSUE TITLE
User-Task-ID header is not found in the response from the server. Question

### ISSUE THREAD

**Issue by AlexandrChikur** [linkedin/cruise-control-ui#93]
Hello everyone, I'm having trouble deploying CC & CCFE and would like to ask for help.
So, I got below error on some tabs of CCFE:
``` User-Task-ID header is not found in the response from the server. ```

I got 3 nodes where zookeeper, kafka, cc & ccfe is deployed on each node.

### Versions

> Kafka 3.1.0
> Scala 2.13
> CC 2.5.89
> CCFE 0.3.4

I configured cruisecontrol.properties as it says [here](https://github.com/linkedin/cruise-control-ui/wiki/CORS-Method)

### cruisecontrol.properties. configurations for the webserver section

> webserver.http.port={{ cruise_control_port }}
> webserver.http.address=0.0.0.0
> webserver.http.cors.enabled=true
> webserver.http.cors.origin=http://localhost:{{ cruise_control_port }}
> webserver.http.cors.allowmethods=OPTIONS,GET,POST
> webserver.http.cors.exposeheaders=User-Task-ID,Content-Type
> webserver.api.urlprefix=/kafkacruisecontrol/*
> webserver.ui.diskpath={{ cruise_control_ui_work_dir }}/dist
> webserver.ui.urlprefix=/*
> webserver.request.maxBlockTimeMs=10000
> webserver.session.maxExpiryTimeMs=60000
> webserver.session.path=/
> webserver.accesslog.enabled=true

In this configuration {{ cruise_control_port }} is 9898.

That's what config.csv Insights says:
![image](https://user-images.githubusercontent.com/52509642/167868970-082f29c9-7f2e-4287-9e9b-3ca3a3fa0a9e.png)

I found User-Task-Id in Response Headers, but still got this error.
![image](https://user-images.githubusercontent.com/52509642/167869634-b59835ef-c027-427f-ba9c-147fd09e1093.png)

Maybe I missed somethig, I'll be really appreciate with any help.

**Comment by nareshv** [comment]
Can you use the latest version from git ?
