### ISSUE TITLE
CORS Issue 

### ISSUE THREAD

**Issue by ravikumar019** [linkedin/cruise-control-ui#94]
CC version-2.0.191
Apache Kafka Version -2.2.1

![Screenshot from 2022-05-23 16-38-52](https://user-images.githubusercontent.com/100900037/170671861-a67720c6-ee2b-48cb-958d-1cbb22b2cc07.png)

Tried by reducing scrape interval less than 30 secs , still getting same error

**Comment by nareshv** [comment]
let the system take some time to catch up with load on kafka cluster after with `/load` would return proper data.

**Comment by ravikumar019** [comment]
facing this issue since last week

**Comment by nareshv** [comment]
GET /load is failing, which will take care of the CORS error

In general for CORS thing, can you see if [v0.4.0](https://github.com/linkedin/cruise-control-ui/releases) version helps you ?
