### ISSUE TITLE
CORS issue on Executor State page if cache headers are included

### ISSUE THREAD

**Issue by desobolevsky** [linkedin/cruise-control-ui#95]
I'm experiencing this issue on Executor State tab, though every other tab and everything in general works perfectly fine.
![image](https://user-images.githubusercontent.com/45672233/183857190-41ba687d-754f-4aad-98fb-ffc6da8c5861.png)
Looks like I get the error on CORS preflight request.
![image](https://user-images.githubusercontent.com/45672233/183857530-c3624671-3add-43b1-aebf-14134ac50f12.png)
Tried to fix this issue myself, removing cache headers from [Executor component](https://github.com/linkedin/cruise-control-ui/blob/master/src/components/Executor.vue#L390) resolves it, Executor tab works good with the request like that:
```
vm.$http.get(vm.url, {withCredentials: true}).then((r) => {
```

Any thoughts on the appearing issue?

CC-UI is on master branch
CC is on migrate_to_kafka_2_5 branch
Kafka: 3.1.1 (Commit:5cf0285dc9728b0b)

**Comment by IronforgeV** [comment]
getting the same error

`Access to XMLHttpRequest at 'https://xxx.com/kafkacruisecontrol/state?substates=EXECUTOR&verbose=true&json=true' from origin 'https://xxxx.com' has been blocked by CORS policy: Request header field cache-buster is not allowed by Access-Control-Allow-Headers in preflight response.`

**Comment by IronforgeV** [comment]
> getting the same error
> 
> `Access to XMLHttpRequest at 'https://xxx.com/kafkacruisecontrol/state?substates=EXECUTOR&verbose=true&json=true' from origin 'https://xxxx.com' has been blocked by CORS policy: Request header field cache-buster is not allowed by Access-Control-Allow-Headers in preflight response.`

fixed by adding Cache-buster to the webserver.http.cors.exposeheaders in cruisecontrol.properties file

`webserver.http.cors.exposeheaders=User-Task-ID,Content-Type,Cache-buster`

**Comment by nareshv** [comment]
@desobolevsky can you raise a PR for this ?

**Comment by desobolevsky** [comment]
@nareshv seems like everything works if Cache-Buster header is specified in cruisecontrol.properties, so I don't think this code needs a correction.
IMO it makes sense to add this header to default cruisecontrol.properties file in cruise-control repository. Any thoughts of that?
If it's ok I'll raise the issue and close this one

**Comment by nareshv** [comment]
yep, lets add this config change to actual CC itself as a PR

**Comment by nareshv** [comment]
created https://github.com/linkedin/cruise-control/issues/1950 and will follow there

**Comment by arunturo** [comment]
Hi,

Even after adding the following property I get the CORS error for Executor State tab

webserver.http.cors.exposeheaders=User-Task-ID,Content-Type,Cache-buster
Access to XMLHttpRequest at 'https://xxx.com/kafkacruisecontrol/state?substates=EXECUTOR&verbose=true&json=true' from origin 'https://xxx.com’ has been blocked by CORS policy: Request header field cache-control is not allowed by Access-Control-Allow-Headers in preflight response.
Do you have any recommendations on how to proceed from here?
